### PR TITLE
Blazeface numpy array incorrect batching

### PR DESCRIPTION
**Pull request by Serega6678**
In brief: incorrect behaviour of blazeface during batching if numpy array is provided was fixed.
I've described this problem in detail in fix_info/bad_behaviour_example.ipynb
Hope you'll merge my pull request because I lost a lot of time due to both incorrect description and behaviour

### CODE REVIEW

**Comment by 1adrianb** [comment]
Hi @Serega6678, thank you for investigating this. I believe that in all cases the input should have the same shape regardless of the data type - in this case (B, C, H, W) since its the default channel ordering in pytorch. I believe that making the function behave differently based on the input type may create more confusion in the feature.

I agree however that the current documentation was not very clear about this, would you be happy to adjust you commit to update the doc of the function to reflect this (ie define the expected input/out shape and type + other explanation that may be useful)?

**Comment by Serega6678** [comment]
@1adrianb of course, I've just updated the description. However, without changing the code the function will still be incorrect: for more details take a look at my .ipynb notebook: you can see that there is only one permutation of numpy batch axes that can be passed to the model without getting an exception during the function execution. This permutation, however, leads to the incorrect answer: the detector thinks that image height (or width, I'm not sure) equals to 3 (initial number of image channels), so I don't think it's possible to make the function correct for numpy arrays without changing the function. More than that, in my commit you can see that image shape equals to B, C, H, W (unlike the only axes permutation which finishes without an exception).
To conclude: my implementation does not rely on data type: shapes are similar among all posible inputs: numpy array, torch.tensor and others. I've already changed the documentation, please take a look and write back if you have any other questions regarding my pull request!

**Comment by 1adrianb** [comment]
Thanks for the clarification, yes, you are right, this is due to the expectation of the resize_and_crop function. Could you remove the content of fix_info please before I can merge this?
Thanks again for looking into this.

**Comment by Serega6678** [comment]
Done! Thank you too

**Review by 1adrianb — APPROVED** [review]

**Pull request merged**
